# -*- coding: utf-8 -*-
"""management.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yLUAkAI-q4xCsb9h1ChkuTrAhJhpryom
"""

class Student:
    def __init__(self, student_id, name, date_of_birth):
        self.student_id = student_id
        self.name = name
        self.date_of_birth = date_of_birth
        self.registered_courses = []

class Course:
    def __init__(self, course_code, title):
        self.course_code = course_code
        self.title = title

class CollegeManagementSystem:
    def __init__(self):
        self.students = []
        self.courses = []

    def register_student(self, student_id, name, date_of_birth):
        new_student = Student(student_id, name, date_of_birth)
        self.students.append(new_student)

    def display_students(self):
        for student in self.students:
            print(f"Student ID: {student.student_id}, Name: {student.name}")

    def update_student_info(self, student_id, new_name, new_date_of_birth):
        for student in self.students:
            if student.student_id == student_id:
                student.name = new_name
                student.date_of_birth = new_date_of_birth

    def add_course(self, course_code, title):
        new_course = Course(course_code, title)
        self.courses.append(new_course)

    def display_courses(self):
        for course in self.courses:
            print(f"Course Code: {course.course_code}, Title: {course.title}")

    def register_course(self, student_id, course_code):
        for student in self.students:
            if student.student_id == student_id:
                for course in self.courses:
                    if course.course_code == course_code and course not in student.registered_courses:
                        student.registered_courses.append(course)
                        print(f"Student {student.name} registered for course {course.title}")
                    elif course.course_code == course_code and course in student.registered_courses:
                        print(f"Student {student.name} is already registered for course {course.title}")
                        return
        else:
            print("Student or course not found.")

    def display_registered_courses(self, student_id):
        for student in self.students:
            if student.student_id == student_id:
                print(f"Registered courses for {student.name}:")
                for course in student.registered_courses:
                    print(f"Course: {course.title}")


# Initialize the College Management System
college_system = CollegeManagementSystem()

while True:
    print("\nWelcome to College Management System")
    print("1. Register Student")
    print("2. Display Students")
    print("3. Update Student Information")
    print("4. Add Course")
    print("5. Display Courses")
    print("6. Register Course")
    print("7. Display Registered Courses")
    print("8. Quit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        student_id = input("Enter student ID: ")
        name = input("Enter student name: ")
        date_of_birth = input("Enter student date of birth: ")
        college_system.register_student(student_id, name, date_of_birth)
    elif choice == 2:
        college_system.display_students()
    elif choice == 3:
        student_id = input("Enter student ID: ")
        new_name = input("Enter new name: ")
        new_date_of_birth = input("Enter new date of birth: ")
        college_system.update_student_info(student_id, new_name, new_date_of_birth)
    elif choice == 4:
        course_code = input("Enter course code: ")
        title = input("Enter course title: ")
        college_system.add_course(course_code, title)
    elif choice == 5:
        college_system.display_courses()
    elif choice == 6:
        student_id = input("Enter student ID: ")
        course_code = input("Enter course code: ")
        college_system.register_course(student_id, course_code)
    elif choice == 7:
        student_id = input("Enter student ID: ")
        college_system.display_registered_courses(student_id)
    elif choice == 8:
        print("Thank you for using the College Management System.")
        break
    else:
        print("Invalid choice. Please select a valid option.")

