# -*- coding: utf-8 -*-
"""hirearichy and k-means.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AaZGECtU0KxaEefi2Q4Q2kG2ruTZciEX
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv("/content/International sale Report.csv")

data.head()

data.info()

data.isna().sum()

data.dropna(inplace = True)

data.describe()

data.isna().sum()

data= data[["CUSTOMER","GROSS AMT"]]

data.info()

from sklearn.cluster import KMeans

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
for column in data.columns:
  if data[column].dtype == "object":
    data[column] = le.fit_transform(data[column])

data.info()

data.head()

from pandas.core.internals.blocks import NumericBlock
inertia = []
for number_of_cluster in range(1,5):
  kmean = KMeans(n_clusters = number_of_cluster)
  kmean.fit(data)
  inertia.append(kmean.inertia_)

plt.plot(range(1,5),inertia,"*r-")

kmean = KMeans(n_clusters=2)
predict = kmean.fit_predict(data)

predict

x = data

plt.scatter(x.iloc[predict == 0,0],x.iloc[predict == 0,1],c="r")
plt.scatter(x.iloc[predict == 1,0],x.iloc[predict == 1,1],c="b")

plt.scatter(kmean.cluster_centers_[:,0],kmean.cluster_centers_[:,1],s = 100, c="black")


plt.ylabel("GROSS AMT")
plt.xlabel("Customer")











